name: Daily OpenAI Job Monitor

on:
  schedule:
    - cron: '0 9 * * *'  # Runs at 9:00 AM UTC daily
  workflow_dispatch:  # Allows manual running for testing

jobs:
  monitor-jobs:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests schedule
    
    - name: Create config file with secrets
      run: |
        cat > config.json << EOF
        {
          "email_enabled": true,
          "email_from": "${{ secrets.EMAIL_FROM }}",
          "email_to": "${{ secrets.EMAIL_TO }}",
          "email_password": "${{ secrets.EMAIL_PASSWORD }}",
          "smtp_server": "smtp.gmail.com",
          "smtp_port": 587,
          "check_time": "09:00",
          "first_run_days": 7,
          "include_remote": [],
          "attach_csv": true
        }
        EOF
    
    - name: Run job monitor
      run: python openai_job_monitor.py --run-once
