name: Daily OpenAI Job Monitor

on:
  schedule:
    - cron: '0 20 * * *'  # 8 PM UTC = 9 AM NZDT
  workflow_dispatch:

jobs:
  monitor-jobs:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Set locale for emoji support
      run: |
        export LANG=en_US.UTF-8
        export LC_ALL=en_US.UTF-8
        sudo apt-get update
        sudo apt-get install -y locales
        sudo locale-gen en_US.UTF-8
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests schedule
    
    - name: Create config file with secrets
      run: |
        cat > config.json << EOF
        {
          "email_enabled": true,
          "email_from": "${{ secrets.EMAIL_FROM }}",
          "email_to": "${{ secrets.EMAIL_TO }}",
          "email_password": "${{ secrets.EMAIL_PASSWORD }}",
          "smtp_server": "smtp.gmail.com",
          "smtp_port": 587,
          "check_time": "09:00",
          "first_run_days": 7,
          "include_remote": [],
          "attach_csv": true
        }
        EOF
    
    - name: Run job monitor
      run: |
        export LANG=en_US.UTF-8
        export LC_ALL=en_US.UTF-8
        python openai_job_monitor.py --run-once
    
    - name: Commit database updates
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add job_data/*.json
        git diff --staged --quiet || git commit -m "Update job database - $(date +'%Y-%m-%d %H:%M:%S')"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
